spring:
  application:
    name: erni-cv-rag

springdoc:
  swagger-ui.path: /swagger
  api-docs.path: /api-docs
  packages-to-scan: ch.erni.ai.demo.cv.rag
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

application:
  cv:
    source-dir: ./data/cv_data/ # important to end with /
  prompt-dir: ./data/prompts/cv/ # important to end with /
  llmstudio:
    base-url: http://localhost:1234/v1
  vector_store:
    pgvector:
      host: localhost
      user: baselone
      port: 8432
      password: baselone
      database: baselone
  huggingface:
    tokenizer:
      - name: text-embedding-nomic-embed-text-v2
        path: nomic-ai/nomic-embed-text-v2-moe
  embedding-model:
    model-name: text-embedding-nomic-embed-text-v2
  chat-model:
    model-name: openai/gpt-oss-120b

langchain4j:
  open-ai:

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG